#!/bin/bash
# Assemble a local apt repository from the packages OBS built, for the ISO build.
#
# The point is closed-loop verification: every DANOS package in the image comes
# from OBS, and OBS in turn built from git HEAD.
#
# Five packages used to be absent from OBS and had to be taken from the old
# local repository. All five are now closed out, so EXTRA_LOCAL_PKGS is empty
# and everything here comes from OBS. See step 3 for what happened to each.
#
# The build configuration needs no change: config/archives/danos.list.chroot
# still points at http://127.0.0.1:8080/; only the directory it serves moves
# here.
#
# One trap worth stating explicitly: the build container uses bridge
# networking, so 127.0.0.1 inside it is the container, not this host. Serving
# this directory from the host leaves live-build fetching from whatever is
# already listening inside the container — which was the old local-repo. The
# HTTP server has to be started inside the container, on this directory.

set -u
# OBS_DIR is where the operational state lives -- dsc/ (generated source
# packages), the osc wrapper, run/ (console sockets), fixes/. It is deliberately
# separate from this toolkit: the scripts are worth keeping in version control,
# 2 GB of build output is not. Override it if your working directory differs.
OBS=${OBS_DIR:-${OBS_DIR:-/home/aikon/danos/.obs}}
OSC="$OBS/osc -A https://api.opensuse.org"
OLD=/home/aikon/danos/build-iso/danos-build/local-repo
NEW=/home/aikon/danos/build-iso/danos-build/obs-repo
PUB=/published/home:i-danos/2608

rm -rf "$NEW"; mkdir -p "$NEW"

echo "== 1. fetch the OBS Packages index =="
timeout 180 $OSC api "$PUB/Packages" < /dev/null 2>/dev/null > "$NEW/.Packages.src"
total=$(grep -c '^Package: ' "$NEW/.Packages.src")
echo "   $total packages"

echo "== 2. download =="
# Filename carries a subdirectory prefix (amd64/xxx.deb, all/xxx.deb), so
# taking the basename is wrong — osc api would then hit the directory and
# return a 25-byte <directory></directory>. The public URL is also faster than
# osc api and follows redirects to a nearby mirror.
DL=https://download.opensuse.org/repositories/home:/i-danos/2608
n=0; fail=0
while read -r f; do
  b=$(basename "$f")
  ok=0
  for try in 1 2 3; do
    if curl -sSL --max-time 300 -o "$NEW/$b" "$DL/$f" 2>/dev/null \
       && [ -s "$NEW/$b" ] && dpkg-deb -f "$NEW/$b" Package >/dev/null 2>&1; then
      ok=1; break
    fi
    sleep 3
  done
  if [ $ok -eq 1 ]; then
    n=$((n+1)); [ $((n % 100)) -eq 0 ] && printf '   %d/%d\n' "$n" "$total"
  else
    echo "   failed: $f" >&2; rm -f "$NEW/$b"; fail=$((fail+1))
  fi
done < <(grep -oP '^Filename: \K.*' "$NEW/.Packages.src")
echo "   $n downloaded, $fail failed"

echo "== 3. supplement from the old local repository (nothing left to add) =="
# All five former gaps are closed, so EXTRA_LOCAL_PKGS is empty and this loop
# is a no-op. Kept so a future gap has somewhere to go.
#   cloud-init  -- the repository is complete and is now built on OBS
#                  (build_order.txt line 43's note did not match reality)
#   iproute     -- the three consumers now depend on iproute2; the stub is gone
#   watchdog x3 -- came from the abandoned vyatta-ipmi and are removed from the
#                  image's package lists
for p in "${EXTRA_LOCAL_PKGS[@]:-}"; do
  [ -n "$p" ] || continue
  for f in "$OLD/${p}_"*.deb; do
    [ -e "$f" ] || continue
    # Match the package name exactly, so cloud-init does not also catch
    # cloud-init-something
    [ "$(dpkg-deb -f "$f" Package 2>/dev/null)" = "$p" ] || continue
    cp "$f" "$NEW/" && printf '   + %s\n' "$(basename "$f")"
  done
done

echo "== 4. generate the index =="
rm -f "$NEW/.Packages.src"
cd "$NEW"
dpkg-scanpackages -m . /dev/null > Packages 2>/dev/null
gzip -9kf Packages
xz -9kf Packages
# apt-ftparchive comes from apt-utils unpacked without root. Release has to be
# generated by it: a hand-written one lacks the self-checksums and apt then
# reports "File has unexpected size".
LD_LIBRARY_PATH=$OBS/opt/usr/lib/x86_64-linux-gnu \
  $OBS/opt/usr/bin/apt-ftparchive \
    -o APT::FTPArchive::Release::Suite=danos \
    -o APT::FTPArchive::Release::Codename=trixie \
    release . > Release
echo "   $(grep -c '^Package: ' Packages) packages, $(du -sh . | cut -f1)"
